quantization:
  use_matquant: True
  use_codistillation: False

  use_qat: False
  fx_mode: False
  
  target_bits: [8, 4, 2]
  loss_weights: {8: 0.4, 4: 0.8, 2: 0.8}

  quantize_bias: True
  quantize_target: "weights_and_activations"  # Options: "weights_only", "activations_only", "weights_and_activations"
  
  quantize_signed: False # Whether to use signed quantization (default: False for unsigned)
        
  ## for evaluating multiple (also untrained) bit-widths
  # target_bits: [8, 7, 6, 5, 4, 3, 2, 1]
  # loss_weights: {8: 0.4, 7: 0.0, 6: 0.0, 5: 0.0, 4: 0.8, 3: 0.0, 2: 0.8, 1: 0.0}

  # # Use --list-layers to get id and path of layers
  # # Index-based selection (less robust)
  # quantize_layers: [0, 1, 2, 3]

  # # Note that only a single model. prefix needs to be specified (--list-layers will show the full path)
  # # Path-based selection (more robust)
  quantize_layers:
    - "model.0.weight"
    - "model.4.weight"
    - "model.9.weight"
    - "model.11.weight"

model:
  name: vgg
  dataset: fashion
  num_channels: 1
  num_blocks: 1  # Number of VGG blocks (Conv+Max+Act and/or Conv+Act)
  kernel_size: 3
  stride: 1
  padding: 1
  input_size: 28
  linear_layers:
    - size: 2048
  num_classes: 10

training:
  model_dir: ./models/vgg/fashion/matquant
  model_savename: q842_mq842_wab
  optimizer: sgd
  batch_size: 64
  num_epochs: 1
  learning_rate: 0.01
  lr_scheduler: cosine
  gamma: 0.1
  step_size: 5
  momentum: 0.9
  weight_decay: 0.0001
  seed: 707  # Random seed for reproducibility

evaluation:
  model_path: ./models/vgg/fashion/matquant/q842_mq842_wab.pt
  # model_path: ./models/vgg/fashion/matquant/checkpoint_avg_89.05_b8_89.47_b4_89.45_b2_88.24.pt
  batch_size: 128
  num_iterations: 1

