quantization:
  use_matquant: true
  use_codistillation: false
  use_qat: false
  fx_mode: false
  target_bits:
  - 8
  - 6
  - 4
  loss_weights:
    8: 0.2
    6: 0.4
    4: 0.6
  quantize_input: true
  quantize_bias: true
  quantize_weight: true
  quantize_activation: true
  quantize_signed: true
  fold_bn_inference: false
  quantized_params_list:
  - all
model:
  name: mlp
  dataset: mnist
  input_size: 28
  hidden_layers:
  - size: 512
  - size: 512
  output_size: 10
  use_hf: false
training:
  model_dir: ./models/mlp/matquant
  model_savename: q864_mq864_wab_s
  dry_iterations: 10
  optimizer: sgd
  batch_size: 256
  num_epochs: 30
  learning_rate: 0.001
  lr_scheduler: cosine
  gamma: 0.1
  step_size: 10
  momentum: 0.9
  weight_decay: 0.0001
  val_split: 0.1
  early_stopping:
    enabled: true
    monitor: test_accuracy
    patience: 5
    min_delta: 0.01
evaluation:
  model_path: ./models-tuned/mlp/q864/best_model.pt
  batch_size: 128
  num_iterations: 1
early_stopping_info:
  epoch: 25
  monitor: test_accuracy
  score: 91.99666666666667
  mode: max
training_metrics:
  epoch_loss: 0.25
  val_loss: 0.49
  test_avg_accuracy: 92.0
  val_avg_accuracy: 91.34
  per_bit_metrics:
    8bit:
      train_loss: 0.21
      train_accuracy: 93.93
      test_top1_accuracy: 91.8
      test_top5_accuracy: 99.7
      test_accuracy: 91.8
      val_loss: 0.4
      val_accuracy: 91.28
    6bit:
      train_loss: 0.21
      train_accuracy: 93.94
      test_top1_accuracy: 91.97
      test_top5_accuracy: 99.72
      test_accuracy: 91.97
      val_loss: 0.41
      val_accuracy: 91.27
    4bit:
      train_loss: 0.21
      train_accuracy: 93.94
      test_top1_accuracy: 92.22
      test_top5_accuracy: 99.72
      test_accuracy: 92.22
      val_loss: 0.41
      val_accuracy: 91.47
