quantization:
  use_matquant: true
  use_codistillation: false
  use_qat: false
  fx_mode: false
  target_bits:
  - 8
  - 6
  - 4
  - 2
  loss_weights:
    8: 0.2
    6: 0.4
    4: 0.6
    2: 0.8
  quantize_input: true
  quantize_bias: false
  quantize_weight: true
  quantize_activation: true
  quantize_signed: true
  fold_bn_inference: false
  quantized_params_list:
  - all
  use_bias: false
model:
  name: mlp
  dataset: mnist
  input_size: 28
  hidden_layers:
  - size: 512
  - size: 512
  output_size: 10
  use_hf: false
  use_batchnorm: false
  use_bias: false
training:
  model_dir: ./models/mlp/matquant
  model_savename: q8642_mq8642_wa_s
  dry_iterations: 10
  optimizer: sgd
  batch_size: 256
  num_epochs: 30
  learning_rate: 0.001
  lr_scheduler: cosine
  gamma: 0.1
  step_size: 10
  momentum: 0.9
  weight_decay: 0.0001
  val_split: 0.1
  early_stopping:
    enabled: true
    monitor: test_accuracy
    patience: 5
    min_delta: 0.01
evaluation:
  model_path: ./models-tuned/mlp/q8642-nobias/best_model.pt
  test_samples: 10000
  batch_size: 128
  num_iterations: 1
  mix_and_match_configs:
  - description: test
    config:
      model.0.weight: 8
      model.0.bias: 8
      model.2.weight: 2
      model.2.bias: 8
      model.4.weight: 2
      model.4.bias: 8
early_stopping_info:
  epoch: 23
  monitor: test_accuracy
  score: 93.875
  mode: max
training_metrics:
  epoch_loss: 0.34
  val_loss: 0.79
  test_avg_accuracy: 93.88
  val_avg_accuracy: 93.2
  per_bit_metrics:
    8bit:
      train_loss: 0.16
      train_accuracy: 95.48
      test_top1_accuracy: 94.07
      test_top5_accuracy: 99.8
      test_accuracy: 94.07
      val_loss: 0.3
      val_accuracy: 93.32
    6bit:
      train_loss: 0.16
      train_accuracy: 95.43
      test_top1_accuracy: 94.08
      test_top5_accuracy: 99.79
      test_accuracy: 94.08
      val_loss: 0.31
      val_accuracy: 93.4
    4bit:
      train_loss: 0.16
      train_accuracy: 95.36
      test_top1_accuracy: 93.98
      test_top5_accuracy: 99.78
      test_accuracy: 93.98
      val_loss: 0.31
      val_accuracy: 93.43
    2bit:
      train_loss: 0.19
      train_accuracy: 95.16
      test_top1_accuracy: 93.37
      test_top5_accuracy: 99.78
      test_accuracy: 93.37
      val_loss: 0.53
      val_accuracy: 92.67
